set -g mouse on
setw -g mode-keys vi
set -g prefix M-\'
set-option -g history-limit 1000000
set -g default-terminal "tmux"
set -as terminal-overrides ',*:sitm=\E[23m:ritm=\E[23m'
set -s copy-command 'sh -c "tee /tmp/tmux-buf | wl-copy 2>/dev/null; DISPLAY=:0 xclip -sel c < /tmp/tmux-buf 2>/dev/null; DISPLAY=:1 xclip -sel c < /tmp/tmux-buf 2>/dev/null; DISPLAY=:2 xclip -sel c < /tmp/tmux-buf 2>/dev/null; pbcopy < /tmp/tmux-buf 2>/dev/null; rm -f /tmp/tmux-buf"'
