set -g extended-keys on
set -g extended-keys-format csi-u
set -g mouse on
setw -g mode-keys vi
set -g prefix M-\'
bind M-\' send-prefix
set-option -g history-limit 1000000
set -g default-terminal "tmux-256color"
set -s copy-command 'xclip -selection clipboard'

bind c new-window -c "#{pane_current_path}"
